version: '3.8'

services:
  backend:
    container_name: backend-ruralin-qas
    build:
      context: .
      dockerfile: Dockerfile.qas
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
