import { Router } from 'express';
import usuarioRoutes from './usuario.routes';
import localRoutes from './local.routes';
import eventoRoutes from './evento.routes';
import pessoaRoutes from './pessoa.routes';
import grupoProdutoRoutes from './grupoProduto.routes';
import subGrupoProdutoRoutes from './subGrupoProduto.routes';
import principioAtivoRoutes from './principioAtivo.routes';
import unidadeMedidaRoutes from './unidadeMedida.routes';
import moedaRoutes from './moeda.routes';
import moedaCotacaoRoutes from './moedaCotacao.routes';
import produtoRoutes from './produto.routes';
import culturaRoutes from './cultura.routes';
import servicoAgricolaRoutes from './servicoAgricola.routes';
import planoContaGerencialRoutes from './planoContaGerencial.routes';
import consultoriaRoutes from './consultoria.routes';
import tenantRoutes from './tenant.routes';
import estadoRoutes from './estado.routes';
import municipioRoutes from './municipio.routes';
import centroCustoRoutes from './centroCusto.routes';
import safraRoutes from './safra.routes';
import fazendaRoutes from './fazenda.routes';
import lembreteRoutes from './lembrete.routes';
import authRoutes from './auth.routes';
import financeiroRoutes from './financeiro.routes';
import roleRoutes from './role.routes';
import permissaoRoutes from './permissao.routes';
import roleHasPermissaoRoutes from './roleHasPermissao.routes';
import { authMiddleware } from '../middleware/auth';
import { tenantActivationMiddleware } from '../middleware/tenantActivation';
import usuarioHasRoleRoutes from './usuarioHasRole.routes';
import usuarioHasSubUsuarioRoutes from './usuarioHasSubUsuario.routes';
import auditLogRoutes from './audit-log.routes';
import cacheMetricsRoutes from './cache-metrics.routes';
import tituloPagarRoutes from './tituloPagar.routes';
import tituloReceberRoutes from './tituloReceber.routes';
import parcelaRoutes from './parcela.routes';
import relatorioFinanceiroRoutes from './relatorioFinanceiro.routes';
import contaRoutes from './conta.routes';
import grupoEquipamentoRoutes from './grupoEquipamento.routes';
import maquinaRoutes from './maquina.routes';
import abastecimentoRoutes from './abastecimento.routes';
import movimentoEstoqueRoutes from './movimentoEstoque.routes';
import talhaoRoutes from './talhao.routes';
import configuradorCicloRoutes from './configuradorCiclo.routes';
import atividadeAgricolaRoutes from './atividadeAgricola.routes';
import atividadeOperacaoRoutes from './atividadeOperacao.routes';
import apontamentoRoutes from './apontamento.routes';
import apontamentoMaquinasRoutes from './apontamentoMaquinas.routes';
import apontamentoProdutoRoutes from './apontamentoProduto.routes';
import apontamentoServicoRoutes from './apontamentoServico.routes';
import benfeitoriaRoutes from './benfeitoria.routes';
import produtoBenfeitoriaRoutes from './produtoBenfeitoria.routes';
import servicoBenfeitoriaRoutes from './servicoBenfeitoria.routes';
import listaBancosRoutes from './listaBancos.routes';
import notaFiscalRoutes from './notaFiscal.routes';
import itemNotaFiscalRoutes from './itemNotaFiscal.routes';
import pedidoCompraRoutes from './pedidoCompra.routes';
import itemPedidoCompraRoutes from './itemPedidoCompra.routes';
import baixaPedidoCompraRoutes from './baixaPedidoCompra.routes';
import itemBaixaPedidoCompraRoutes from './itemBaixaPedidoCompra.routes';
import emprestimoRoutes from './emprestimo.routes';
import emprestimoItemRoutes from './emprestimoItem.routes';
import emprestimoItemDevolucaoRoutes from './emprestimoItemDevolucao.routes';
import outraDespesaReceitaRoutes from './outraDespesaReceita.routes';
import unidadeDepositoRoutes from './unidadeDeposito.routes';
import registroArmazenagemRoutes from './registroArmazenagem.routes';
import agreementRoutes from './agreement.routes';
import recorrenciaFinanceiraRoutes from './recorrenciaFinanceira.routes';
import alertaVencimentoConfigRoutes from './alertaVencimentoConfig.routes';
import agingReportRoutes from './agingReport.routes';
import fluxoCaixaRoutes from './fluxoCaixa.routes';
import numeracaoReciboRoutes from './numeracaoRecibo.routes';
import configuracaoReciboRoutes from './configuracaoRecibo.routes';
import reciboRoutes from './recibo.routes';
import tipoAtividadeOSRoutes from './tipoAtividadeOS.routes';
import ordemServicoRoutes from './ordemServico.routes';
import cfopRoutes from './cfop.routes';
import certificadoDigitalRoutes from './certificadoDigital.routes';
import cotacaoRoutes from './cotacao.routes';
import numeracaoNfeRoutes from './numeracaoNfe.routes';

const router = Router();

router.get('/', (req, res) => {
  res.json({ message: 'API is running' });
});

router.use('/auth', authRoutes);

// Protected routes
// Aplicar tenantActivationMiddleware após authMiddleware para verificar status de tenant/consultoria
router.use('/usuarios', authMiddleware, tenantActivationMiddleware, usuarioRoutes);
router.use('/locais', authMiddleware, tenantActivationMiddleware, localRoutes);
router.use('/eventos', authMiddleware, tenantActivationMiddleware, eventoRoutes);
router.use('/pessoas', authMiddleware, tenantActivationMiddleware, pessoaRoutes);
router.use('/gruposProduto', authMiddleware, tenantActivationMiddleware, grupoProdutoRoutes);
router.use('/subGruposProduto', authMiddleware, tenantActivationMiddleware, subGrupoProdutoRoutes);
router.use('/principiosAtivo', authMiddleware, tenantActivationMiddleware, principioAtivoRoutes);
router.use('/unidadesMedida', authMiddleware, tenantActivationMiddleware, unidadeMedidaRoutes);
router.use('/moedas', authMiddleware, tenantActivationMiddleware, moedaRoutes);
router.use('/moedasCotacao', authMiddleware, tenantActivationMiddleware, moedaCotacaoRoutes);
router.use('/produtos', authMiddleware, tenantActivationMiddleware, produtoRoutes);
router.use('/culturas', authMiddleware, tenantActivationMiddleware, culturaRoutes);
router.use('/servicosAgricola', authMiddleware, tenantActivationMiddleware, servicoAgricolaRoutes);
router.use('/planoContasGerenciais', authMiddleware, tenantActivationMiddleware, planoContaGerencialRoutes);
router.use('/consultorias', authMiddleware, consultoriaRoutes); // Consultorias não precisam de tenantActivation (GOD gerencia)
router.use('/tenants', authMiddleware, tenantActivationMiddleware, tenantRoutes);
router.use('/estados', authMiddleware, estadoRoutes); // Estados são dados globais - não precisam de tenantActivation
router.use('/municipios', authMiddleware, municipioRoutes); // Municípios são dados globais - não precisam de tenantActivation
router.use('/listaBancos', authMiddleware, listaBancosRoutes); // Lista de Bancos são dados globais - não precisam de tenantActivation
router.use('/centrosCusto', authMiddleware, tenantActivationMiddleware, centroCustoRoutes);
router.use('/safras', authMiddleware, tenantActivationMiddleware, safraRoutes);
router.use('/fazendas', authMiddleware, tenantActivationMiddleware, fazendaRoutes);
router.use('/lembretes', authMiddleware, tenantActivationMiddleware, lembreteRoutes);
router.use('/financeiro', authMiddleware, tenantActivationMiddleware, financeiroRoutes);
router.use('/roles', authMiddleware, roleRoutes);
router.use('/permissoes', authMiddleware, permissaoRoutes);
router.use('/roleHasPermissoes', authMiddleware, roleHasPermissaoRoutes);
router.use('/usuario-roles', authMiddleware, usuarioHasRoleRoutes);
router.use('/usuario-subusuarios', authMiddleware, usuarioHasSubUsuarioRoutes);
router.use('/audit-logs', authMiddleware, auditLogRoutes);
router.use('/cache', authMiddleware, cacheMetricsRoutes);
router.use('/titulosPagar', authMiddleware, tenantActivationMiddleware, tituloPagarRoutes);
router.use('/titulosReceber', authMiddleware, tenantActivationMiddleware, tituloReceberRoutes);
router.use('/parcelas', authMiddleware, tenantActivationMiddleware, parcelaRoutes);
router.use('/relatorios', authMiddleware, tenantActivationMiddleware, relatorioFinanceiroRoutes);
router.use('/contas', authMiddleware, tenantActivationMiddleware, contaRoutes);
router.use('/gruposEquipamento', authMiddleware, tenantActivationMiddleware, grupoEquipamentoRoutes);
router.use('/maquinas', authMiddleware, tenantActivationMiddleware, maquinaRoutes);
router.use('/abastecimentos', authMiddleware, tenantActivationMiddleware, abastecimentoRoutes);
router.use('/movimentosEstoque', authMiddleware, tenantActivationMiddleware, movimentoEstoqueRoutes);
router.use('/talhoes', authMiddleware, tenantActivationMiddleware, talhaoRoutes);
router.use('/configuradoresCiclo', authMiddleware, tenantActivationMiddleware, configuradorCicloRoutes);
router.use('/atividadesAgricola', authMiddleware, tenantActivationMiddleware, atividadeAgricolaRoutes);
router.use('/atividadesOperacao', authMiddleware, tenantActivationMiddleware, atividadeOperacaoRoutes);
router.use('/apontamentos', authMiddleware, tenantActivationMiddleware, apontamentoRoutes);
router.use('/apontamentosMaquinas', authMiddleware, tenantActivationMiddleware, apontamentoMaquinasRoutes);
router.use('/apontamentosProduto', authMiddleware, tenantActivationMiddleware, apontamentoProdutoRoutes);
router.use('/apontamentosServico', authMiddleware, tenantActivationMiddleware, apontamentoServicoRoutes);
router.use('/benfeitorias', authMiddleware, tenantActivationMiddleware, benfeitoriaRoutes);
router.use('/produtosBenfeitoria', authMiddleware, tenantActivationMiddleware, produtoBenfeitoriaRoutes);
router.use('/servicosBenfeitoria', authMiddleware, tenantActivationMiddleware, servicoBenfeitoriaRoutes);
router.use('/notasFiscais', authMiddleware, tenantActivationMiddleware, notaFiscalRoutes);
router.use('/itensNotaFiscal', authMiddleware, tenantActivationMiddleware, itemNotaFiscalRoutes);
router.use('/pedidosCompra', authMiddleware, tenantActivationMiddleware, pedidoCompraRoutes);
router.use('/itensPedidoCompra', authMiddleware, tenantActivationMiddleware, itemPedidoCompraRoutes);
router.use('/baixasPedidoCompra', authMiddleware, tenantActivationMiddleware, baixaPedidoCompraRoutes);
router.use('/itensBaixaPedidoCompra', authMiddleware, tenantActivationMiddleware, itemBaixaPedidoCompraRoutes);
router.use('/emprestimos', authMiddleware, tenantActivationMiddleware, emprestimoRoutes);
router.use('/emprestimoItens', authMiddleware, tenantActivationMiddleware, emprestimoItemRoutes);
router.use('/emprestimoItensDevolucao', authMiddleware, tenantActivationMiddleware, emprestimoItemDevolucaoRoutes);
router.use('/outrasDespesasReceitas', authMiddleware, tenantActivationMiddleware, outraDespesaReceitaRoutes);
router.use('/unidadesDeposito', authMiddleware, tenantActivationMiddleware, unidadeDepositoRoutes);
router.use('/registrosArmazenagem', authMiddleware, tenantActivationMiddleware, registroArmazenagemRoutes);
router.use('/agreements', authMiddleware, tenantActivationMiddleware, agreementRoutes);
router.use('/recorrenciasFinanceiras', authMiddleware, tenantActivationMiddleware, recorrenciaFinanceiraRoutes);
router.use('/alertasVencimentoConfig', authMiddleware, tenantActivationMiddleware, alertaVencimentoConfigRoutes);
router.use('/agingReports', authMiddleware, tenantActivationMiddleware, agingReportRoutes);
router.use('/fluxo-caixa', authMiddleware, tenantActivationMiddleware, fluxoCaixaRoutes);
router.use('/numeracao-recibos', authMiddleware, tenantActivationMiddleware, numeracaoReciboRoutes);
router.use('/configuracao-recibos', authMiddleware, tenantActivationMiddleware, configuracaoReciboRoutes);
router.use('/recibos', authMiddleware, tenantActivationMiddleware, reciboRoutes);
router.use('/tipos-atividade-os', authMiddleware, tenantActivationMiddleware, tipoAtividadeOSRoutes);
router.use('/ordens-servico', authMiddleware, tenantActivationMiddleware, ordemServicoRoutes);

router.use('/cfops', authMiddleware, cfopRoutes); // CFOPs são dados globais - não precisam de tenantActivation
router.use('/certificados-digitais', authMiddleware, tenantActivationMiddleware, certificadoDigitalRoutes);
router.use('/cotacoes', authMiddleware, tenantActivationMiddleware, cotacaoRoutes);
router.use('/numeracoesNfe', authMiddleware, tenantActivationMiddleware, numeracaoNfeRoutes);

export default router;
