# Estágio de build
FROM node:22-alpine AS build-stage

# Habilitar corepack para suporte ao pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Definir diretório de trabalho
WORKDIR /app

# Copiar arquivos de dependência
COPY package.json pnpm-lock.yaml ./

# Instalar dependências
RUN pnpm install --frozen-lockfile

# Copiar o restante dos arquivos do projeto
COPY . .

# Passar a URL da API como argumento
ARG VITE_RURALIN_API_URL
ENV VITE_RURALIN_API_URL="https://api-teste.ruralin.cloud/api"

ARG VITE_MAPBOX_TOKEN
ENV VITE_MAPBOX_TOKEN="pk.eyJ1IjoidGhpYWdvYXQiLCJhIjoiY21tMm9uY291MDluczJ4bjhiamJubXUwbCJ9.dZapnl7XKqaKWMUlUemDjg"

# Construir a aplicação para produção
RUN pnpm run build

# Estágio de produção
FROM nginx:alpine AS production-stage

# Copiar os arquivos construídos do estágio anterior
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Copiar configuração personalizada do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expor a porta 80
EXPOSE 80

# Iniciar o Nginx
CMD ["nginx", "-g", "daemon off;"]
